---
- name: Main entry point for this playbook
  hosts: webservers
  vars_files:
    - vars/external_vars.yml
  user: "{{ username }}"

  roles:
    - virtualenv
    #- common-python
    - nginx
    - uwsgi
    - aps_project
    - supervisor
